### ISSUE TITLE
Mô tả Dự Án TravelPlan Web - App

### ISSUE THREAD

**Issue by jenniferANT** [jenniferANT/TravelPlan_project#1]
Định nghĩa đề tài / Mô tả tổng quan dự án/ Trình bày các chức năng chính

**Comment by jenniferANT** [comment]
Link Docs : [Định nghĩa đề tài OOSE - Google Tài liệu](https://docs.google.com/document/d/1_aZBQKEwBwoCM5W_VzcUpxUZGGEP0mqZsqV-gmuXH-I/edit)

**Comment by Ngoc-Tu** [comment]
![Image](https://github.com/jenniferANT/TravelPlan_project/assets/93045620/1557fd16-ed86-4efc-badf-f4bd41ac21a0)

**Comment by Ngoc-Tu** [comment]
![Image](https://github.com/jenniferANT/TravelPlan_project/assets/93045620/07a9b8f4-7036-4e01-b02c-853e9137c2fe)
